@startuml

class agent
agent --> common
integrationtests --> common
integrationtests --> master
integrationtests --> agent
integrationtests --> mocks
master --> common
masterrunner --> mocks
masterrunner --> master
mocks --> common
mocks --> master
mocks --> agent
sourcesrepository --> sourcesrepositorycommon
sourcesrepositoryrunner --> sourcesrepository
webapp --> common
webapp --> sourcesrepositorycommon
master --> agent : uploads to build server


@enduml
